package remembertheporter.invconfig.init;

import net.minecraft.core.registries.Registries;
import net.minecraft.world.entity.ai.attributes.Attribute;
import net.minecraft.world.entity.ai.attributes.RangedAttribute;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.RegistryObject;
import remembertheporter.invconfig.InvConfig;

public class ModAttributes {
    public static final DeferredRegister<Attribute> ATTRIBUTES = DeferredRegister.create(Registries.ATTRIBUTE, InvConfig.MODID);
    public static final RegistryObject<Attribute> SLOTS = ATTRIBUTES.register("slots", () -> new RangedAttribute("invconfig.slots",0,-64,64).setSyncable(true));
    public static final RegistryObject<Attribute> HOTBAR_SLOTS = ATTRIBUTES.register("hotbar_slots", () -> new RangedAttribute("invconfig.hotbar_slots",0,-64,64).setSyncable(true));
    public static final RegistryObject<Attribute> SLOT_0 = ATTRIBUTES.register("slot_0", () -> new RangedAttribute("invconfig.slot_0",0,-64,64).setSyncable(true));
    public static final RegistryObject<Attribute> SLOT_1 = ATTRIBUTES.register("slot_1", () -> new RangedAttribute("invconfig.slot_1",0,-64,64).setSyncable(true));
    public static final RegistryObject<Attribute> SLOT_2 = ATTRIBUTES.register("slot_2", () -> new RangedAttribute("invconfig.slot_2",0,-64,64).setSyncable(true));
    public static final RegistryObject<Attribute> SLOT_3 = ATTRIBUTES.register("slot_3", () -> new RangedAttribute("invconfig.slot_3",0,-64,64).setSyncable(true));
    public static final RegistryObject<Attribute> SLOT_4 = ATTRIBUTES.register("slot_4", () -> new RangedAttribute("invconfig.slot_4",0,-64,64).setSyncable(true));
    public static final RegistryObject<Attribute> SLOT_5 = ATTRIBUTES.register("slot_5", () -> new RangedAttribute("invconfig.slot_5",0,-64,64).setSyncable(true));
    public static final RegistryObject<Attribute> SLOT_6 = ATTRIBUTES.register("slot_6", () -> new RangedAttribute("invconfig.slot_6",0,-64,64).setSyncable(true));
    public static final RegistryObject<Attribute> SLOT_7 = ATTRIBUTES.register("slot_7", () -> new RangedAttribute("invconfig.slot_7",0,-64,64).setSyncable(true));
    public static final RegistryObject<Attribute> SLOT_8 = ATTRIBUTES.register("slot_8", () -> new RangedAttribute("invconfig.slot_8",0,-64,64).setSyncable(true));
    public static final RegistryObject<Attribute> SLOT_9 = ATTRIBUTES.register("slot_9", () -> new RangedAttribute("invconfig.slot_9",0,-64,64).setSyncable(true));
    public static final RegistryObject<Attribute> SLOT_10 = ATTRIBUTES.register("slot_10", () -> new RangedAttribute("invconfig.slot_10",0,-64,64).setSyncable(true));
    public static final RegistryObject<Attribute> SLOT_11 = ATTRIBUTES.register("slot_11", () -> new RangedAttribute("invconfig.slot_11",0,-64,64).setSyncable(true));
    public static final RegistryObject<Attribute> SLOT_12 = ATTRIBUTES.register("slot_12", () -> new RangedAttribute("invconfig.slot_12",0,-64,64).setSyncable(true));
    public static final RegistryObject<Attribute> SLOT_13 = ATTRIBUTES.register("slot_13", () -> new RangedAttribute("invconfig.slot_13",0,-64,64).setSyncable(true));
    public static final RegistryObject<Attribute> SLOT_14 = ATTRIBUTES.register("slot_14", () -> new RangedAttribute("invconfig.slot_14",0,-64,64).setSyncable(true));
    public static final RegistryObject<Attribute> SLOT_15 = ATTRIBUTES.register("slot_15", () -> new RangedAttribute("invconfig.slot_15",0,-64,64).setSyncable(true));
    public static final RegistryObject<Attribute> SLOT_16 = ATTRIBUTES.register("slot_16", () -> new RangedAttribute("invconfig.slot_16",0,-64,64).setSyncable(true));
    public static final RegistryObject<Attribute> SLOT_17 = ATTRIBUTES.register("slot_17", () -> new RangedAttribute("invconfig.slot_17",0,-64,64).setSyncable(true));
    public static final RegistryObject<Attribute> SLOT_18 = ATTRIBUTES.register("slot_18", () -> new RangedAttribute("invconfig.slot_18",0,-64,64).setSyncable(true));
    public static final RegistryObject<Attribute> SLOT_19 = ATTRIBUTES.register("slot_19", () -> new RangedAttribute("invconfig.slot_19",0,-64,64).setSyncable(true));
    public static final RegistryObject<Attribute> SLOT_20 = ATTRIBUTES.register("slot_20", () -> new RangedAttribute("invconfig.slot_20",0,-64,64).setSyncable(true));
    public static final RegistryObject<Attribute> SLOT_21 = ATTRIBUTES.register("slot_21", () -> new RangedAttribute("invconfig.slot_21",0,-64,64).setSyncable(true));
    public static final RegistryObject<Attribute> SLOT_22 = ATTRIBUTES.register("slot_22", () -> new RangedAttribute("invconfig.slot_22",0,-64,64).setSyncable(true));
    public static final RegistryObject<Attribute> SLOT_23 = ATTRIBUTES.register("slot_23", () -> new RangedAttribute("invconfig.slot_23",0,-64,64).setSyncable(true));
    public static final RegistryObject<Attribute> SLOT_24 = ATTRIBUTES.register("slot_24", () -> new RangedAttribute("invconfig.slot_24",0,-64,64).setSyncable(true));
    public static final RegistryObject<Attribute> SLOT_25 = ATTRIBUTES.register("slot_25", () -> new RangedAttribute("invconfig.slot_25",0,-64,64).setSyncable(true));
    public static final RegistryObject<Attribute> SLOT_26 = ATTRIBUTES.register("slot_26", () -> new RangedAttribute("invconfig.slot_26",0,-64,64).setSyncable(true));
    public static final RegistryObject<Attribute> SLOT_27 = ATTRIBUTES.register("slot_27", () -> new RangedAttribute("invconfig.slot_27",0,-64,64).setSyncable(true));
    public static final RegistryObject<Attribute> SLOT_28 = ATTRIBUTES.register("slot_28", () -> new RangedAttribute("invconfig.slot_28",0,-64,64).setSyncable(true));
    public static final RegistryObject<Attribute> SLOT_29 = ATTRIBUTES.register("slot_29", () -> new RangedAttribute("invconfig.slot_29",0,-64,64).setSyncable(true));
    public static final RegistryObject<Attribute> SLOT_30 = ATTRIBUTES.register("slot_30", () -> new RangedAttribute("invconfig.slot_30",0,-64,64).setSyncable(true));
    public static final RegistryObject<Attribute> SLOT_31 = ATTRIBUTES.register("slot_31", () -> new RangedAttribute("invconfig.slot_31",0,-64,64).setSyncable(true));
    public static final RegistryObject<Attribute> SLOT_32 = ATTRIBUTES.register("slot_32", () -> new RangedAttribute("invconfig.slot_32",0,-64,64).setSyncable(true));
    public static final RegistryObject<Attribute> SLOT_33 = ATTRIBUTES.register("slot_33", () -> new RangedAttribute("invconfig.slot_33",0,-64,64).setSyncable(true));
    public static final RegistryObject<Attribute> SLOT_34 = ATTRIBUTES.register("slot_34", () -> new RangedAttribute("invconfig.slot_34",0,-64,64).setSyncable(true));
    public static final RegistryObject<Attribute> SLOT_35 = ATTRIBUTES.register("slot_35", () -> new RangedAttribute("invconfig.slot_35",0,-64,64).setSyncable(true));
    public static final RegistryObject<Attribute> OFFHAND_SLOT = ATTRIBUTES.register("offhand_slot", () -> new RangedAttribute("invconfig.offhand_slot",0,-64,64).setSyncable(true));
    public static final RegistryObject<Attribute> HEAD_SLOT = ATTRIBUTES.register("head_slot", () -> new RangedAttribute("invconfig.head_slot",0,-64,64).setSyncable(true));
    public static final RegistryObject<Attribute> CHEST_SLOT = ATTRIBUTES.register("chest_slot", () -> new RangedAttribute("invconfig.chest_slot",0,-64,64).setSyncable(true));
    public static final RegistryObject<Attribute> LEGS_SLOT = ATTRIBUTES.register("legs_slot", () -> new RangedAttribute("invconfig.legs_slot",0,-64,64).setSyncable(true));
    public static final RegistryObject<Attribute> FEET_SLOT = ATTRIBUTES.register("feet_slot", () -> new RangedAttribute("invconfig.feet_slot",0,-64,64).setSyncable(true));
    public static final RegistryObject<Attribute> CRAFT_TOP_LEFT_SLOT = ATTRIBUTES.register("crafting_top_left_slot", () -> new RangedAttribute("invconfig.crafting_top_left_slot",0,-64,64).setSyncable(true));
    public static final RegistryObject<Attribute> CRAFT_TOP_RIGHT_SLOT = ATTRIBUTES.register("crafting_top_right_slot", () -> new RangedAttribute("invconfig.crafting_top_right_slot",0,-64,64).setSyncable(true));
    public static final RegistryObject<Attribute> CRAFT_BOTTOM_LEFT_SLOT = ATTRIBUTES.register("crafting_bottom_left_slot", () -> new RangedAttribute("invconfig.crafting_bottom_left_slot",0,-64,64).setSyncable(true));
    public static final RegistryObject<Attribute> CRAFT_BOTTOM_RIGHT_SLOT = ATTRIBUTES.register("crafting_bottom_right_slot", () -> new RangedAttribute("invconfig.crafting_bottom_right_slot",0,-64,64).setSyncable(true));
}
